var types = ds_list_create()

ds_list_add(types,obj_clubs_A)
ds_list_add(types,obj_clubs_2)
ds_list_add(types,obj_clubs_3)
ds_list_add(types,obj_clubs_4)
ds_list_add(types,obj_clubs_5)
ds_list_add(types,obj_clubs_6)
ds_list_add(types,obj_clubs_7)
ds_list_add(types,obj_clubs_8)
ds_list_add(types,obj_clubs_9)
ds_list_add(types,obj_clubs_10)
ds_list_add(types,obj_clubs_J)
ds_list_add(types,obj_clubs_Q)
ds_list_add(types,obj_clubs_K)

ds_list_add(types,obj_hearts_A)
ds_list_add(types,obj_hearts_2)
ds_list_add(types,obj_hearts_3)
ds_list_add(types,obj_hearts_4)
ds_list_add(types,obj_hearts_5)
ds_list_add(types,obj_hearts_6)
ds_list_add(types,obj_hearts_7)
ds_list_add(types,obj_hearts_8)
ds_list_add(types,obj_hearts_9)
ds_list_add(types,obj_hearts_10)
ds_list_add(types,obj_hearts_J)
ds_list_add(types,obj_hearts_Q)
ds_list_add(types,obj_hearts_K)

ds_list_add(types,obj_diamonds_A)
ds_list_add(types,obj_diamonds_2)
ds_list_add(types,obj_diamonds_3)
ds_list_add(types,obj_diamonds_4)
ds_list_add(types,obj_diamonds_5)
ds_list_add(types,obj_diamonds_6)
ds_list_add(types,obj_diamonds_7)
ds_list_add(types,obj_diamonds_8)
ds_list_add(types,obj_diamonds_9)
ds_list_add(types,obj_diamonds_10)
ds_list_add(types,obj_diamonds_J)
ds_list_add(types,obj_diamonds_Q)
ds_list_add(types,obj_diamonds_K)

ds_list_add(types,obj_spades_A)
ds_list_add(types,obj_spades_2)
ds_list_add(types,obj_spades_3)
ds_list_add(types,obj_spades_4)
ds_list_add(types,obj_spades_5)
ds_list_add(types,obj_spades_6)
ds_list_add(types,obj_spades_7)
ds_list_add(types,obj_spades_8)
ds_list_add(types,obj_spades_9)
ds_list_add(types,obj_spades_10)
ds_list_add(types,obj_spades_J)
ds_list_add(types,obj_spades_Q)
ds_list_add(types,obj_spades_K)

return types;